name: Android CI

on:
  push:
    branches-ignore:
      - 'flashlight-experiment'
  pull_request:
    branches-ignore:
      - 'flashlight-experiment'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble the Debug .apk
      run: ./gradlew assembleDebug
    - name: Create and Release the Debug artifact
      uses: actions/upload-artifact@v3
      with:
        name: osudroid-rx-debug
        path: build/outputs/apk/debug/app-debug.apk
    - name: Assemble the Release .apk
      run: ./gradlew assembleRelease
    - name: Create and Release the main artifact
      uses: actions/upload-artifact@v3
      with:
        name: osudroid-rx
        path: build/outputs/apk/debug/app-release.apk
